---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: netology
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            mode: 0644
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            mode: 0644
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Copying Clickhouse config
      become: true
      ansible.builtin.template:
        mode: 0644
        src: templates/clickhouse_config.xml.j2
        dest: /etc/clickhouse-server/config.xml
      notify: restart-clickhouse-service
    - name: Copying Clickhouse users
      become: true
      ansible.builtin.template:
        mode: 0644
        src: templates/clickhouse_users.xml.j2
        dest: /etc/clickhouse-server/users.xml
      notify: restart-clickhouse-service
    - name: Start clickhouse service
      become: true
      ansible.builtin.systemd:
        name: clickhouse-server
        state: started
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
    - name: Create table
      ansible.builtin.command: clickhouse-client -q 'CREATE TABLE vector_logs.logs_messages ("message" String) ENGINE = Log'
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc !=57
      changed_when: create_table.rc == 0
- name: Vector installation
  hosts: vector
  remote_user: centos
  tasks:
    - name: Install additional tools
      become: true
      ansible.builtin.yum:
        name:
          - "libstdc++"
          - "glibc"
        state: present
    - name: Downloading Vector distributives
      ansible.builtin.get_url:
        mode: 0644
        url: "https://packages.timber.io/vector/0.21.1/{{ vector_latest }}.rpm"
        dest: "/tmp/{{ vector_latest }}.rpm"
    - name: Install Vector packages
      become: true
      ansible.builtin.yum:
        name: "/tmp/{{ vector_latest }}.rpm"
        state: present
    - name: Start vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: started      
    - name: copy Vector config
      become: true
      ansible.builtin.template:
        mode: 0644
        src: templates/vector.yaml.j2
        dest: "{{ vector_config_dest }}"
        # owner: "{{ ansible_user_id }}"
        # group: "{{ ansible_user_gid }}"
        backup: true
        validate: vector validate --no-environment --config-yaml %s          
...
