---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: netology
  roles:
    - clickhouse_role
    
- name: Vector installation
  hosts: vector
  remote_user: netology
  roles:
    - vector_role

- name: Lighthouse installation
  hosts: lighthouse
  remote_user: netology
  roles:
    - lighthouse_role
...
