---
- name: Copying Clickhouse config
  become: true
  ansible.builtin.template:
    mode: 0644
    src: templates/clickhouse_config.xml.j2
    dest: /etc/clickhouse-server/config.xml
  notify: Start clickhouse service
- name: Copying Clickhouse users
  become: true
  ansible.builtin.template:
    mode: 0644
    src: templates/clickhouse_users.xml.j2
    dest: /etc/clickhouse-server/users.xml
  notify: Start clickhouse service
- name: Start clickhouse service
  become: true
  ansible.builtin.systemd:
    name: clickhouse-server
    state: started
- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0
- name: Create table
  ansible.builtin.command: clickhouse-client -q 'CREATE TABLE logs.logs_messages ("message" String) ENGINE = Log'
  register: create_table
  failed_when: create_table.rc != 0 and create_table.rc != 57
  changed_when: create_table.rc == 0