---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.35.89
    jenkins-agent-01:
      ansible_host: 158.160.39.165
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology
    ansible_ssh_private_key_file: ../../../id_rsa