{
 "title": "Netology",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\",device!~'rootfs',fstype!='tmpfs',mountpoint='/'}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\",device!~'rootfs',fstype!='tmpfs',mountpoint='/'}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Load Avarage 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "Load Avarage 5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "Load Avarage 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}[5m])))) * 100"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Free RAM"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Available RAM"
    }
   ]
  }
 ]
}