---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.5.4
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology
    ansible_ssh_private_key_file: ../../../id_rsa