---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-8
    image: filipp0vap/centos8-python39:latest
    pre_build_image: true
  - name: ubuntu
    image: filipp0vap/ubuntu-python:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
