version: '2.1'

services:
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    volumes:
      - ./example:/example
  maven:
    image: maven:latest
    volumes:
      - ./mvn:/opt/data/mvn
