---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos-8-podman
    image: localhost/centos8-python39:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
