---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: netology
  roles:
    - clickhouse-role
    
- name: Vector installation
  hosts: vector
  remote_user: netology
  roles:
    - vector-role

- name: Lighthouse installation
  hosts: lighthouse
  remote_user: netology
  roles:
    - lighthouse-role
...
