filebeat.inputs:
  - type: container
    # enabled: true
    # encoding: utf-8
    # json.add_error_key: true
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true
  # - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
